### ISSUE TITLE
[BUG] Time counter going below zero when given 0 as an argument

### ISSUE THREAD

**Issue by aaryanajaysharma** [Voicedrew11/time-tan#2]
When asked how much time I want to study, I gave 0 as an argument, expecting it'll directly prompt to the search result of the anime I want to watch.

But this is what I got
<img width="474" alt="image" src="https://user-images.githubusercontent.com/78302134/226265849-e84366ee-1eef-4682-8f27-24cc496b428f.png">

I think this just a minor issue which can be solved by writing an if condition.

**Comment by Voicedrew11** [comment]
Good catch!
