### ISSUE TITLE
[TODO!] Use flags.

### ISSUE THREAD

**Issue by Voicedrew11** [Voicedrew11/time-tan#4]
Add CLI options that allow users to specify certain parameters from the command line.

--time  -t (specify study period)
--anime -a (specify anime)

**Comment by starguyaman** [comment]
Looks exicting! Can I contribute?

**Comment by Voicedrew11** [comment]
@buggyprogrammer 

Go for it.

https://docs.python.org/3/library/argparse.html

**Comment by starguyaman** [comment]
Thanks, I'll try to complete fast :)

**Comment by Voicedrew11** [comment]
Completed by @buggyprogrammer in #5
